CREATE TABLE IF NOT EXISTS movie_images (
  id INT AUTO_INCREMENT PRIMARY KEY,
  movie_id INT NOT NULL,
  image_path VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (movie_id) REFERENCES movies(id) ON DELETE CASCADE
); 